twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        peintureRepository: "@App\\Repository\\PeintureRepository"


when@test:
    twig:
        strict_variables: true




