vich_uploader:
    db_driver: orm

    mappings:
        peinture_images:
            uri_prefix: '%peinture_images%'
            upload_destination: '%kernel.project_dir%/public%sculpture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false        
        sculpture_images:
            uri_prefix: '%sculpture_images%'
            upload_destination: '%kernel.project_dir%/public%sculpture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
